{% from "dockers/dockerfile-macros.j2" import install_debian_packages, install_python_wheels, copy_files %}
FROM docker-config-engine-buster

ARG docker_container_name
RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update

{% if docker_teamd_debs.strip() -%}
# Copy locally-built Debian package dependencies
{{ copy_files("debs/", docker_teamd_debs.split(' '), "/debs/") }}

# Install locally-built Debian packages and implicitly install their dependencies
{{ install_debian_packages(docker_teamd_debs.split(' ')) }}
{%- endif %}

# W/A: install python2
RUN apt-get -y --no-install-recommends install python2.7 python-pip

# W/A: upgrade pip via PyPI and uninstall the Debian version
RUN pip2 install --upgrade pip

# W/A: setuptools and wheel are necessary for installing some Python wheel packages
RUN pip2 install --no-cache-dir setuptools==44.1.1
RUN pip2 install --no-cache-dir wheel==0.35.1

# W/A: install supervisor
RUN pip2 install supervisor==4.2.1

# W/A: add support for supervisord to handle startup dependencies
RUN pip2 install supervisord-dependent-startup==1.4.0

RUN apt-get clean -y      && \
    apt-get autoclean -y  && \
    apt-get autoremove -y && \
    rm -rf /debs

COPY ["start.sh", "/usr/bin/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]
COPY ["files/supervisor-proc-exit-listener", "/usr/bin"]
COPY ["critical_processes", "/etc/supervisor"]

ENTRYPOINT ["/usr/local/bin/supervisord"]
