# Mellanox ASIC syncd

MLNX_ASIC_SYNCD_VERSION = 1.0.0000

export MLNX_ASIC_SYNCD_VERSION

MLNX_ASIC_SYNCD = mlnx-asic-syncd_1.mlnx.$(MLNX_ASIC_SYNCD_VERSION)_amd64.deb
$(MLNX_ASIC_SYNCD)_SRC_PATH = $(PLATFORM_PATH)/mlnx-asic-syncd
SONIC_MAKE_DEBS += $(MLNX_ASIC_SYNCD)

SONIC_STRETCH_DEBS += $(MLNX_ASIC_SYNCD)
